-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    real_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    real_r_ce0 : OUT STD_LOGIC;
    real_r_we0 : OUT STD_LOGIC;
    real_r_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    real_r_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    real_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    real_r_ce1 : OUT STD_LOGIC;
    real_r_we1 : OUT STD_LOGIC;
    real_r_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    real_r_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    img_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    img_ce0 : OUT STD_LOGIC;
    img_we0 : OUT STD_LOGIC;
    img_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    img_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    img_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    img_ce1 : OUT STD_LOGIC;
    img_we1 : OUT STD_LOGIC;
    img_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    img_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    real_twid_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    real_twid_ce0 : OUT STD_LOGIC;
    real_twid_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    img_twid_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    img_twid_ce0 : OUT STD_LOGIC;
    img_twid_q0 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of fft is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fft,hls_ip_2016_4,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.232000,HLS_SYN_LAT=130581,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=56,HLS_SYN_FF=4296,HLS_SYN_LUT=7601}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (24 downto 0) := "0000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (24 downto 0) := "0000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (24 downto 0) := "0000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (24 downto 0) := "0000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (24 downto 0) := "0000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (24 downto 0) := "0001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (24 downto 0) := "0010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (24 downto 0) := "0100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv30_200 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000001000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv22_1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_198 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal reg_206 : STD_LOGIC_VECTOR (63 downto 0);
    signal odd_cast_fu_214_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal odd_cast_reg_325 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal log_cast2_cast_fu_218_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal log_cast2_cast_reg_332 : STD_LOGIC_VECTOR (9 downto 0);
    signal log_1_fu_228_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal log_1_reg_340 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_fu_238_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_12_reg_345 : STD_LOGIC_VECTOR (9 downto 0);
    signal exitcond_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal odd_1_fu_264_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal odd_1_reg_353 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal real_addr_reg_358 : STD_LOGIC_VECTOR (9 downto 0);
    signal real_addr_1_reg_364 : STD_LOGIC_VECTOR (9 downto 0);
    signal img_addr_reg_370 : STD_LOGIC_VECTOR (9 downto 0);
    signal img_addr_1_reg_376 : STD_LOGIC_VECTOR (9 downto 0);
    signal rootindex_fu_291_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal rootindex_reg_382 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_16_fu_306_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal real_load_1_reg_393 : STD_LOGIC_VECTOR (63 downto 0);
    signal img_load_1_reg_399 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_166_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal temp_reg_405 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_fu_170_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_5_reg_410 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_174_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal temp_1_reg_415 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_178_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_7_reg_420 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_9_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_425 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal real_twid_load_reg_439 : STD_LOGIC_VECTOR (63 downto 0);
    signal img_twid_load_reg_445 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_182_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_reg_451 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal grp_fu_186_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_reg_456 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_190_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_6_reg_461 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_194_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_10_reg_466 : STD_LOGIC_VECTOR (63 downto 0);
    signal temp_2_reg_471 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal tmp_11_reg_476 : STD_LOGIC_VECTOR (63 downto 0);
    signal odd_2_fu_320_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal odd_reg_134 : STD_LOGIC_VECTOR (29 downto 0);
    signal log_reg_146 : STD_LOGIC_VECTOR (3 downto 0);
    signal odd1_reg_157 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_279_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_285_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_fu_315_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_166_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_166_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal grp_fu_170_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_170_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal tmp_fu_234_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_14_fu_244_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_15_fu_260_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal even_fu_269_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal even_cast_fu_274_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_17_fu_296_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_166_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_170_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (24 downto 0);

    component fft_dadddsub_64nsbkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component fft_dadd_64ns_64ncud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component fft_dsub_64ns_64ndEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component fft_dmul_64ns_64neOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    fft_dadddsub_64nsbkb_U1 : component fft_dadddsub_64nsbkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_166_p0,
        din1 => grp_fu_166_p1,
        opcode => grp_fu_166_opcode,
        ce => ap_const_logic_1,
        dout => grp_fu_166_p2);

    fft_dadddsub_64nsbkb_U2 : component fft_dadddsub_64nsbkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_170_p0,
        din1 => grp_fu_170_p1,
        opcode => grp_fu_170_opcode,
        ce => ap_const_logic_1,
        dout => grp_fu_170_p2);

    fft_dadd_64ns_64ncud_U3 : component fft_dadd_64ns_64ncud
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_206,
        din1 => img_load_1_reg_399,
        ce => ap_const_logic_1,
        dout => grp_fu_174_p2);

    fft_dsub_64ns_64ndEe_U4 : component fft_dsub_64ns_64ndEe
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_206,
        din1 => img_load_1_reg_399,
        ce => ap_const_logic_1,
        dout => grp_fu_178_p2);

    fft_dmul_64ns_64neOg_U5 : component fft_dmul_64ns_64neOg
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => real_twid_load_reg_439,
        din1 => reg_198,
        ce => ap_const_logic_1,
        dout => grp_fu_182_p2);

    fft_dmul_64ns_64neOg_U6 : component fft_dmul_64ns_64neOg
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => img_twid_load_reg_445,
        din1 => reg_206,
        ce => ap_const_logic_1,
        dout => grp_fu_186_p2);

    fft_dmul_64ns_64neOg_U7 : component fft_dmul_64ns_64neOg
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => real_twid_load_reg_439,
        din1 => reg_206,
        ce => ap_const_logic_1,
        dout => grp_fu_190_p2);

    fft_dmul_64ns_64neOg_U8 : component fft_dmul_64ns_64neOg
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => img_twid_load_reg_445,
        din1 => reg_198,
        ce => ap_const_logic_1,
        dout => grp_fu_194_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    log_reg_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state3) and (ap_const_lv1_0 = icmp_fu_254_p2))) then 
                log_reg_146 <= log_1_reg_340;
            elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then 
                log_reg_146 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    odd1_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state25))) then 
                odd1_reg_157 <= odd_2_fu_320_p2;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state2) and (exitcond_fu_222_p2 = ap_const_lv1_0))) then 
                odd1_reg_157 <= odd_cast_fu_214_p1;
            end if; 
        end if;
    end process;

    odd_reg_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state3) and (ap_const_lv1_0 = icmp_fu_254_p2))) then 
                odd_reg_134 <= tmp_16_fu_306_p1;
            elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then 
                odd_reg_134 <= ap_const_lv30_200;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state3) and not((ap_const_lv1_0 = icmp_fu_254_p2)))) then
                img_addr_1_reg_376 <= tmp_3_fu_285_p1(10 - 1 downto 0);
                img_addr_reg_370 <= tmp_2_fu_279_p1(10 - 1 downto 0);
                odd_1_reg_353 <= odd_1_fu_264_p2;
                real_addr_1_reg_364 <= tmp_3_fu_285_p1(10 - 1 downto 0);
                real_addr_reg_358 <= tmp_2_fu_279_p1(10 - 1 downto 0);
                rootindex_reg_382 <= rootindex_fu_291_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state4))) then
                img_load_1_reg_399 <= img_q1;
                real_load_1_reg_393 <= real_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state13))) then
                img_twid_load_reg_445 <= img_twid_q0;
                real_twid_load_reg_439 <= real_twid_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state2))) then
                log_1_reg_340 <= log_1_fu_228_p2;
                    log_cast2_cast_reg_332(3 downto 0) <= log_cast2_cast_fu_218_p1(3 downto 0);
                odd_cast_reg_325 <= odd_cast_fu_214_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_lv1_1 = ap_CS_fsm_state4)) or ((ap_const_lv1_1 = ap_CS_fsm_state13)))) then
                reg_198 <= real_r_q0;
                reg_206 <= img_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state9))) then
                temp_1_reg_415 <= grp_fu_174_p2;
                temp_reg_405 <= grp_fu_166_p2;
                tmp_5_reg_410 <= grp_fu_170_p2;
                tmp_7_reg_420 <= grp_fu_178_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state24))) then
                temp_2_reg_471 <= grp_fu_166_p2;
                tmp_11_reg_476 <= grp_fu_170_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state19))) then
                tmp_10_reg_466 <= grp_fu_194_p2;
                tmp_1_reg_451 <= grp_fu_182_p2;
                tmp_4_reg_456 <= grp_fu_186_p2;
                tmp_6_reg_461 <= grp_fu_190_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state2) and (exitcond_fu_222_p2 = ap_const_lv1_0))) then
                tmp_12_reg_345 <= tmp_12_fu_238_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state11))) then
                tmp_9_reg_425 <= tmp_9_fu_310_p2;
            end if;
        end if;
    end process;
    log_cast2_cast_reg_332(9 downto 4) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, exitcond_fu_222_p2, icmp_fu_254_p2, tmp_9_fu_310_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (not((exitcond_fu_222_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if ((ap_const_lv1_0 = icmp_fu_254_p2)) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (not((ap_const_lv1_0 = tmp_9_fu_310_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state25;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9 downto 9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10 downto 10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11 downto 11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12 downto 12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13 downto 13);
    ap_CS_fsm_state19 <= ap_CS_fsm(18 downto 18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1 downto 1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19 downto 19);
    ap_CS_fsm_state24 <= ap_CS_fsm(23 downto 23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24 downto 24);
    ap_CS_fsm_state3 <= ap_CS_fsm(2 downto 2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3 downto 3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4 downto 4);
    ap_CS_fsm_state9 <= ap_CS_fsm(8 downto 8);

    ap_done_assign_proc : process(ap_CS_fsm_state2, exitcond_fu_222_p2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state2) and not((exitcond_fu_222_p2 = ap_const_lv1_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond_fu_222_p2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state2) and not((exitcond_fu_222_p2 = ap_const_lv1_0)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    even_cast_fu_274_p2 <= (tmp_15_fu_260_p1 and tmp_12_reg_345);
    even_fu_269_p2 <= (odd_1_fu_264_p2 xor odd_cast_reg_325);
    exitcond_fu_222_p2 <= "1" when (log_reg_146 = ap_const_lv4_A) else "0";

    grp_fu_166_opcode_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state20)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state20))) then 
            grp_fu_166_opcode <= ap_const_lv2_1;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            grp_fu_166_opcode <= ap_const_lv2_0;
        else 
            grp_fu_166_opcode <= "XX";
        end if; 
    end process;


    grp_fu_166_p0_assign_proc : process(reg_198, tmp_1_reg_451, ap_CS_fsm_state5, ap_CS_fsm_state20)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state20))) then 
            grp_fu_166_p0 <= tmp_1_reg_451;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            grp_fu_166_p0 <= reg_198;
        else 
            grp_fu_166_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_166_p1_assign_proc : process(real_load_1_reg_393, tmp_4_reg_456, ap_CS_fsm_state5, ap_CS_fsm_state20)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state20))) then 
            grp_fu_166_p1 <= tmp_4_reg_456;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            grp_fu_166_p1 <= real_load_1_reg_393;
        else 
            grp_fu_166_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_170_opcode_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state20)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            grp_fu_170_opcode <= ap_const_lv2_1;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state20))) then 
            grp_fu_170_opcode <= ap_const_lv2_0;
        else 
            grp_fu_170_opcode <= "XX";
        end if; 
    end process;


    grp_fu_170_p0_assign_proc : process(reg_198, tmp_6_reg_461, ap_CS_fsm_state5, ap_CS_fsm_state20)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state20))) then 
            grp_fu_170_p0 <= tmp_6_reg_461;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            grp_fu_170_p0 <= reg_198;
        else 
            grp_fu_170_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_170_p1_assign_proc : process(real_load_1_reg_393, tmp_10_reg_466, ap_CS_fsm_state5, ap_CS_fsm_state20)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state20))) then 
            grp_fu_170_p1 <= tmp_10_reg_466;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            grp_fu_170_p1 <= real_load_1_reg_393;
        else 
            grp_fu_170_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_fu_254_p2 <= "1" when (signed(tmp_14_fu_244_p4) < signed(ap_const_lv22_1)) else "0";

    img_address0_assign_proc : process(ap_CS_fsm_state3, img_addr_1_reg_376, ap_CS_fsm_state12, tmp_2_fu_279_p1, ap_CS_fsm_state10)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state12)) or ((ap_const_lv1_1 = ap_CS_fsm_state10)))) then 
            img_address0 <= img_addr_1_reg_376;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state3))) then 
            img_address0 <= tmp_2_fu_279_p1(10 - 1 downto 0);
        else 
            img_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    img_address1_assign_proc : process(ap_CS_fsm_state3, img_addr_reg_370, img_addr_1_reg_376, ap_CS_fsm_state11, ap_CS_fsm_state25, tmp_3_fu_285_p1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state25))) then 
            img_address1 <= img_addr_1_reg_376;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state11))) then 
            img_address1 <= img_addr_reg_370;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state3))) then 
            img_address1 <= tmp_3_fu_285_p1(10 - 1 downto 0);
        else 
            img_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    img_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state12, ap_CS_fsm_state10)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state3)) or ((ap_const_lv1_1 = ap_CS_fsm_state12)) or ((ap_const_lv1_1 = ap_CS_fsm_state10)))) then 
            img_ce0 <= ap_const_logic_1;
        else 
            img_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    img_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state25)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state3)) or ((ap_const_lv1_1 = ap_CS_fsm_state11)) or ((ap_const_lv1_1 = ap_CS_fsm_state25)))) then 
            img_ce1 <= ap_const_logic_1;
        else 
            img_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    img_d0 <= tmp_7_reg_420;

    img_d1_assign_proc : process(temp_1_reg_415, ap_CS_fsm_state11, tmp_11_reg_476, ap_CS_fsm_state25)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state25))) then 
            img_d1 <= tmp_11_reg_476;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state11))) then 
            img_d1 <= temp_1_reg_415;
        else 
            img_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    img_twid_address0 <= tmp_s_fu_315_p1(9 - 1 downto 0);

    img_twid_ce0_assign_proc : process(ap_CS_fsm_state12)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state12))) then 
            img_twid_ce0 <= ap_const_logic_1;
        else 
            img_twid_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    img_we0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state10)))) then 
            img_we0 <= ap_const_logic_1;
        else 
            img_we0 <= ap_const_logic_0;
        end if; 
    end process;


    img_we1_assign_proc : process(tmp_9_reg_425, ap_CS_fsm_state11, ap_CS_fsm_state25)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state11)) or ((ap_const_lv1_1 = ap_CS_fsm_state25) and (ap_const_lv1_0 = tmp_9_reg_425)))) then 
            img_we1 <= ap_const_logic_1;
        else 
            img_we1 <= ap_const_logic_0;
        end if; 
    end process;

    log_1_fu_228_p2 <= std_logic_vector(unsigned(log_reg_146) + unsigned(ap_const_lv4_1));
    log_cast2_cast_fu_218_p1 <= std_logic_vector(resize(unsigned(log_reg_146),10));
    odd_1_fu_264_p2 <= (odd1_reg_157 or odd_cast_reg_325);
    odd_2_fu_320_p2 <= std_logic_vector(unsigned(odd_1_reg_353) + unsigned(ap_const_lv32_1));
        odd_cast_fu_214_p1 <= std_logic_vector(resize(signed(odd_reg_134),32));


    real_r_address0_assign_proc : process(ap_CS_fsm_state3, real_addr_1_reg_364, ap_CS_fsm_state12, tmp_2_fu_279_p1, ap_CS_fsm_state10)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state12)) or ((ap_const_lv1_1 = ap_CS_fsm_state10)))) then 
            real_r_address0 <= real_addr_1_reg_364;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state3))) then 
            real_r_address0 <= tmp_2_fu_279_p1(10 - 1 downto 0);
        else 
            real_r_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    real_r_address1_assign_proc : process(ap_CS_fsm_state3, real_addr_reg_358, real_addr_1_reg_364, ap_CS_fsm_state11, ap_CS_fsm_state25, tmp_3_fu_285_p1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state25))) then 
            real_r_address1 <= real_addr_1_reg_364;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state11))) then 
            real_r_address1 <= real_addr_reg_358;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state3))) then 
            real_r_address1 <= tmp_3_fu_285_p1(10 - 1 downto 0);
        else 
            real_r_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    real_r_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state12, ap_CS_fsm_state10)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state3)) or ((ap_const_lv1_1 = ap_CS_fsm_state12)) or ((ap_const_lv1_1 = ap_CS_fsm_state10)))) then 
            real_r_ce0 <= ap_const_logic_1;
        else 
            real_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    real_r_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state25)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state3)) or ((ap_const_lv1_1 = ap_CS_fsm_state11)) or ((ap_const_lv1_1 = ap_CS_fsm_state25)))) then 
            real_r_ce1 <= ap_const_logic_1;
        else 
            real_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    real_r_d0 <= tmp_5_reg_410;

    real_r_d1_assign_proc : process(temp_reg_405, ap_CS_fsm_state11, temp_2_reg_471, ap_CS_fsm_state25)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state25))) then 
            real_r_d1 <= temp_2_reg_471;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state11))) then 
            real_r_d1 <= temp_reg_405;
        else 
            real_r_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    real_r_we0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state10)))) then 
            real_r_we0 <= ap_const_logic_1;
        else 
            real_r_we0 <= ap_const_logic_0;
        end if; 
    end process;


    real_r_we1_assign_proc : process(tmp_9_reg_425, ap_CS_fsm_state11, ap_CS_fsm_state25)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state11)) or ((ap_const_lv1_1 = ap_CS_fsm_state25) and (ap_const_lv1_0 = tmp_9_reg_425)))) then 
            real_r_we1 <= ap_const_logic_1;
        else 
            real_r_we1 <= ap_const_logic_0;
        end if; 
    end process;

    real_twid_address0 <= tmp_s_fu_315_p1(9 - 1 downto 0);

    real_twid_ce0_assign_proc : process(ap_CS_fsm_state12)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state12))) then 
            real_twid_ce0 <= ap_const_logic_1;
        else 
            real_twid_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    rootindex_fu_291_p2 <= std_logic_vector(shift_left(unsigned(even_cast_fu_274_p2),to_integer(unsigned('0' & log_cast2_cast_reg_332(10-1 downto 0)))));
    tmp_12_fu_238_p2 <= (tmp_fu_234_p1 xor ap_const_lv10_3FF);
    tmp_14_fu_244_p4 <= odd1_reg_157(31 downto 10);
    tmp_15_fu_260_p1 <= odd1_reg_157(10 - 1 downto 0);
        tmp_16_fu_306_p1 <= std_logic_vector(resize(signed(tmp_17_fu_296_p4),30));

    tmp_17_fu_296_p4 <= odd_reg_134(29 downto 1);
        tmp_2_fu_279_p1 <= std_logic_vector(resize(signed(even_fu_269_p2),64));

        tmp_3_fu_285_p1 <= std_logic_vector(resize(signed(odd_1_fu_264_p2),64));

    tmp_9_fu_310_p2 <= "1" when (rootindex_reg_382 = ap_const_lv10_0) else "0";
    tmp_fu_234_p1 <= odd_reg_134(10 - 1 downto 0);
    tmp_s_fu_315_p1 <= std_logic_vector(resize(unsigned(rootindex_reg_382),64));
end behav;
