// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "real_r"
#define AUTOTB_TVIN_real_r  "../tv/cdatafile/c.fft.autotvin_real_r.dat"
#define AUTOTB_TVOUT_real_r  "../tv/cdatafile/c.fft.autotvout_real_r.dat"
// wrapc file define: "img"
#define AUTOTB_TVIN_img  "../tv/cdatafile/c.fft.autotvin_img.dat"
#define AUTOTB_TVOUT_img  "../tv/cdatafile/c.fft.autotvout_img.dat"
// wrapc file define: "real_twid"
#define AUTOTB_TVIN_real_twid  "../tv/cdatafile/c.fft.autotvin_real_twid.dat"
// wrapc file define: "img_twid"
#define AUTOTB_TVIN_img_twid  "../tv/cdatafile/c.fft.autotvin_img_twid.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "real_r"
#define AUTOTB_TVOUT_PC_real_r  "../tv/rtldatafile/rtl.fft.autotvout_real_r.dat"
// tvout file define: "img"
#define AUTOTB_TVOUT_PC_img  "../tv/rtldatafile/rtl.fft.autotvout_img.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			real_r_depth = 0;
			img_depth = 0;
			real_twid_depth = 0;
			img_twid_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{real_r " << real_r_depth << "}\n";
			total_list << "{img " << img_depth << "}\n";
			total_list << "{real_twid " << real_twid_depth << "}\n";
			total_list << "{img_twid " << img_twid_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int real_r_depth;
		int img_depth;
		int real_twid_depth;
		int img_twid_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern "C" void fft (
double real[1024],
double img[1024],
double real_twid[512],
double img_twid[512]);

extern "C" void AESL_WRAP_fft (
double real[1024],
double img[1024],
double real_twid[512],
double img_twid[512])
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "real_r"
		aesl_fh.read(AUTOTB_TVOUT_PC_real_r, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_real_r, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_real_r, AESL_token); // data

			sc_bv<64> *real_r_pc_buffer = new sc_bv<64>[1024];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'real_r', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'real_r', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					real_r_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_real_r, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_real_r))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: real_r
				{
					// bitslice(63, 0)
					// {
						// celement: real(63, 0)
						// {
							sc_lv<64>* real_lv0_0_1023_1 = new sc_lv<64>[1024];
						// }
					// }

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: real(63, 0)
						{
							// carray: (0) => (1023) @ (1)
							for (int i_0 = 0; i_0 <= 1023; i_0 += 1)
							{
								if (&(real[0]) != NULL) // check the null address if the c port is array or others
								{
									real_lv0_0_1023_1[hls_map_index++].range(63, 0) = sc_bv<64>(real_r_pc_buffer[hls_map_index].range(63, 0));
								}
							}
						}
					}

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: real(63, 0)
						{
							// carray: (0) => (1023) @ (1)
							for (int i_0 = 0; i_0 <= 1023; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : real[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : real[0]
								// output_left_conversion : *(long long*)&real[i_0]
								// output_type_conversion : (real_lv0_0_1023_1[hls_map_index++]).to_uint64()
								if (&(real[0]) != NULL) // check the null address if the c port is array or others
								{
									*(long long*)&real[i_0] = (real_lv0_0_1023_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] real_r_pc_buffer;
		}

		// output port post check: "img"
		aesl_fh.read(AUTOTB_TVOUT_PC_img, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_img, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_img, AESL_token); // data

			sc_bv<64> *img_pc_buffer = new sc_bv<64>[1024];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'img', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'img', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					img_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_img, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_img))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: img
				{
					// bitslice(63, 0)
					// {
						// celement: img(63, 0)
						// {
							sc_lv<64>* img_lv0_0_1023_1 = new sc_lv<64>[1024];
						// }
					// }

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: img(63, 0)
						{
							// carray: (0) => (1023) @ (1)
							for (int i_0 = 0; i_0 <= 1023; i_0 += 1)
							{
								if (&(img[0]) != NULL) // check the null address if the c port is array or others
								{
									img_lv0_0_1023_1[hls_map_index++].range(63, 0) = sc_bv<64>(img_pc_buffer[hls_map_index].range(63, 0));
								}
							}
						}
					}

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: img(63, 0)
						{
							// carray: (0) => (1023) @ (1)
							for (int i_0 = 0; i_0 <= 1023; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : img[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : img[0]
								// output_left_conversion : *(long long*)&img[i_0]
								// output_type_conversion : (img_lv0_0_1023_1[hls_map_index++]).to_uint64()
								if (&(img[0]) != NULL) // check the null address if the c port is array or others
								{
									*(long long*)&img[i_0] = (img_lv0_0_1023_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] img_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "real_r"
		char* tvin_real_r = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_real_r);
		char* tvout_real_r = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_real_r);

		// "img"
		char* tvin_img = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_img);
		char* tvout_img = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_img);

		// "real_twid"
		char* tvin_real_twid = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_real_twid);

		// "img_twid"
		char* tvin_img_twid = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_img_twid);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_real_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_real_r, tvin_real_r);

		sc_bv<64>* real_r_tvin_wrapc_buffer = new sc_bv<64>[1024];

		// RTL Name: real_r
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: real(63, 0)
				{
					// carray: (0) => (1023) @ (1)
					for (int i_0 = 0; i_0 <= 1023; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : real[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : real[0]
						// regulate_c_name       : real
						// input_type_conversion : *(long long*)&real[i_0]
						if (&(real[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> real_tmp_mem;
							real_tmp_mem = *(long long*)&real[i_0];
							real_r_tvin_wrapc_buffer[hls_map_index++].range(63, 0) = real_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1024; i++)
		{
			sprintf(tvin_real_r, "%s\n", (real_r_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_real_r, tvin_real_r);
		}

		tcl_file.set_num(1024, &tcl_file.real_r_depth);
		sprintf(tvin_real_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_real_r, tvin_real_r);

		// release memory allocation
		delete [] real_r_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_img, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_img, tvin_img);

		sc_bv<64>* img_tvin_wrapc_buffer = new sc_bv<64>[1024];

		// RTL Name: img
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: img(63, 0)
				{
					// carray: (0) => (1023) @ (1)
					for (int i_0 = 0; i_0 <= 1023; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : img[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : img[0]
						// regulate_c_name       : img
						// input_type_conversion : *(long long*)&img[i_0]
						if (&(img[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> img_tmp_mem;
							img_tmp_mem = *(long long*)&img[i_0];
							img_tvin_wrapc_buffer[hls_map_index++].range(63, 0) = img_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1024; i++)
		{
			sprintf(tvin_img, "%s\n", (img_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_img, tvin_img);
		}

		tcl_file.set_num(1024, &tcl_file.img_depth);
		sprintf(tvin_img, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_img, tvin_img);

		// release memory allocation
		delete [] img_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_real_twid, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_real_twid, tvin_real_twid);

		sc_bv<64>* real_twid_tvin_wrapc_buffer = new sc_bv<64>[512];

		// RTL Name: real_twid
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: real_twid(63, 0)
				{
					// carray: (0) => (511) @ (1)
					for (int i_0 = 0; i_0 <= 511; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : real_twid[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : real_twid[0]
						// regulate_c_name       : real_twid
						// input_type_conversion : *(long long*)&real_twid[i_0]
						if (&(real_twid[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> real_twid_tmp_mem;
							real_twid_tmp_mem = *(long long*)&real_twid[i_0];
							real_twid_tvin_wrapc_buffer[hls_map_index++].range(63, 0) = real_twid_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 512; i++)
		{
			sprintf(tvin_real_twid, "%s\n", (real_twid_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_real_twid, tvin_real_twid);
		}

		tcl_file.set_num(512, &tcl_file.real_twid_depth);
		sprintf(tvin_real_twid, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_real_twid, tvin_real_twid);

		// release memory allocation
		delete [] real_twid_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_img_twid, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_img_twid, tvin_img_twid);

		sc_bv<64>* img_twid_tvin_wrapc_buffer = new sc_bv<64>[512];

		// RTL Name: img_twid
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: img_twid(63, 0)
				{
					// carray: (0) => (511) @ (1)
					for (int i_0 = 0; i_0 <= 511; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : img_twid[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : img_twid[0]
						// regulate_c_name       : img_twid
						// input_type_conversion : *(long long*)&img_twid[i_0]
						if (&(img_twid[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> img_twid_tmp_mem;
							img_twid_tmp_mem = *(long long*)&img_twid[i_0];
							img_twid_tvin_wrapc_buffer[hls_map_index++].range(63, 0) = img_twid_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 512; i++)
		{
			sprintf(tvin_img_twid, "%s\n", (img_twid_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_img_twid, tvin_img_twid);
		}

		tcl_file.set_num(512, &tcl_file.img_twid_depth);
		sprintf(tvin_img_twid, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_img_twid, tvin_img_twid);

		// release memory allocation
		delete [] img_twid_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		fft(real, img, real_twid, img_twid);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_real_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_real_r, tvout_real_r);

		sc_bv<64>* real_r_tvout_wrapc_buffer = new sc_bv<64>[1024];

		// RTL Name: real_r
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: real(63, 0)
				{
					// carray: (0) => (1023) @ (1)
					for (int i_0 = 0; i_0 <= 1023; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : real[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : real[0]
						// regulate_c_name       : real
						// input_type_conversion : *(long long*)&real[i_0]
						if (&(real[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> real_tmp_mem;
							real_tmp_mem = *(long long*)&real[i_0];
							real_r_tvout_wrapc_buffer[hls_map_index++].range(63, 0) = real_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1024; i++)
		{
			sprintf(tvout_real_r, "%s\n", (real_r_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_real_r, tvout_real_r);
		}

		tcl_file.set_num(1024, &tcl_file.real_r_depth);
		sprintf(tvout_real_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_real_r, tvout_real_r);

		// release memory allocation
		delete [] real_r_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_img, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_img, tvout_img);

		sc_bv<64>* img_tvout_wrapc_buffer = new sc_bv<64>[1024];

		// RTL Name: img
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: img(63, 0)
				{
					// carray: (0) => (1023) @ (1)
					for (int i_0 = 0; i_0 <= 1023; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : img[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : img[0]
						// regulate_c_name       : img
						// input_type_conversion : *(long long*)&img[i_0]
						if (&(img[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> img_tmp_mem;
							img_tmp_mem = *(long long*)&img[i_0];
							img_tvout_wrapc_buffer[hls_map_index++].range(63, 0) = img_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1024; i++)
		{
			sprintf(tvout_img, "%s\n", (img_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_img, tvout_img);
		}

		tcl_file.set_num(1024, &tcl_file.img_depth);
		sprintf(tvout_img, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_img, tvout_img);

		// release memory allocation
		delete [] img_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "real_r"
		delete [] tvin_real_r;
		delete [] tvout_real_r;
		// release memory allocation: "img"
		delete [] tvin_img;
		delete [] tvout_img;
		// release memory allocation: "real_twid"
		delete [] tvin_real_twid;
		// release memory allocation: "img_twid"
		delete [] tvin_img_twid;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

