# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jsk_027/Thesis/machsuite_fft_workspace/solution1/impl/verilog/fft.xdc

# IP: ip/fft_ap_dmul_4_max_dsp_64/fft_ap_dmul_4_max_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_ap_dmul_4_max_dsp_64 || ORIG_REF_NAME==fft_ap_dmul_4_max_dsp_64}]

# IP: ip/fft_ap_dadd_3_full_dsp_64/fft_ap_dadd_3_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_ap_dadd_3_full_dsp_64 || ORIG_REF_NAME==fft_ap_dadd_3_full_dsp_64}]

# IP: ip/fft_ap_dsub_3_full_dsp_64/fft_ap_dsub_3_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_ap_dsub_3_full_dsp_64 || ORIG_REF_NAME==fft_ap_dsub_3_full_dsp_64}]

# IP: ip/fft_ap_dadddsub_3_full_dsp_64/fft_ap_dadddsub_3_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_ap_dadddsub_3_full_dsp_64 || ORIG_REF_NAME==fft_ap_dadddsub_3_full_dsp_64}]
