// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_fft (
double real[1024],
double img[1024],
double real_twid[512],
double img_twid[512]);
